#!/usr/bin/env python3
"""Write notes/numbers.tex from notes/validation_results.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
jpath = ROOT / "notes" / "validation_results.json"
out = ROOT / "notes" / "numbers.tex"

data = json.loads(jpath.read_text(encoding="utf-8"))
arms = data["arms"]
ref = data["reference"]

# Infer T from traj if present
T = arms["G0"].get("T", 1000)
event = arms["G0"].get("event_at") or arms["G0"].get("split", T // 2)
R = arms["G0"].get("R", 25)
B = arms["G0"].get("n_surr", 99)


def fmt(x, nd=4):
    if x is None:
        return "--"
    if isinstance(x, float):
        if abs(x) >= 0.01 or x == 0.0:
            return f"{x:.{nd}f}"
        return f"{x:.2e}"
    return str(x)


def frac(x):
    return f"{100*x:.0f}\\%"


lines = [
    "% Auto-generated by scripts/fill_numbers_from_json.py — do not edit by hand",
    f"\\newcommand{{\\NumT}}{{{T}}}",
    f"\\newcommand{{\\NumEvent}}{{{event}}}",
    f"\\newcommand{{\\NumR}}{{{R}}}",
    f"\\newcommand{{\\NumB}}{{{B}}}",
    "",
]

for key, prefix in [("G0", "Gzero"), ("G1", "Gone"), ("G2", "Gtwo"), ("G3", "Gthree")]:
    a = arms[key]
    lines += [
        f"% {key}",
        f"\\newcommand{{\\{prefix}Pre}}{{{fmt(a['mean_excess_pre'])}}}",
        f"\\newcommand{{\\{prefix}Post}}{{{fmt(a['mean_excess_post'])}}}",
        f"\\newcommand{{\\{prefix}Delta}}{{{a['mean_delta']:+.4f}}}",
        f"\\newcommand{{\\{prefix}MedP}}{{{fmt(a['median_p'], 3)}}}",
        f"\\newcommand{{\\{prefix}Frac}}{{{frac(a['frac_p_lt_0.05'])}}}",
        f"\\newcommand{{\\{prefix}OccPost}}{{{fmt(a['mean_phi3_occ_post'], 3)}}}",
        "",
    ]

out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out}")
